services:
  postgres:
    image: postgres:17.2
    container_name: loadpocket-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: loadpocket
      POSTGRES_PASSWORD: loadpocket
      POSTGRES_DB: loadpocket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    container_name: loadpocket-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
